service: BookIT
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam: 
    role: ${env:AWS_IAM_ROLE}

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getRooms:
    handler: functions/getRooms/index.handler
    events:
      - httpApi:
          path: '/rooms'
          method: GET

  getRoom:
    handler: functions/getRoomById/index.handler
    events:
      - httpApi:
          path: '/rooms/{roomId}'
          method: GET

  postRoom:
    handler: functions/postRoom/index.handler
    events:
      - httpApi:
          path: '/rooms'
          method: POST

  deleteRoom:
    handler: functions/deleteRoom/index.handler
    events:
      - httpApi:
          path: '/rooms/{roomId}'
          method: DELETE

  bookRoom:
    handler: functions/bookRoom/index.handler
    events:
      - httpApi:
          path: '/bookings/{roomId}'
          method: POST

  deleteBooking:
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: '/rooms/bookings/{bookingId}'
          method: DELETE




resources:
  Resources:
    bookitDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST